swagger: '2.0'
info:
  title: Products API
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get All Products
      operationId: get_all_products_api_products_get
      responses:
        '200':
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /api/products/{code}:
    get:
      summary: Get Product
      operationId: get_product_api_products__code__get
      parameters:
        - name: code
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful Response
          schema:
            $ref: '#/definitions/Product'
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
definitions:
  HTTPValidationError:
    type: object
    properties:
      detail:
        type: array
        items:
          $ref: '#/definitions/ValidationError'
  Product:
    type: object
    required:
      - code
      - name
      - stock
      - category
      - price
      - date
      - manufacturer
      - email
      - country
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
      stock:
        type: number
      category:
        type: string
      price:
        type: number
      date:
        type: string
      manufacturer:
        type: string
      email:
        type: string
      country:
        type: string
  ValidationError:
    type: object
    required:
      - loc
      - msg
      - type
    properties:
      loc:
        type: array
        items:
          type: string
      msg:
        type: string
      type:
        type: string